"use client";

import { Clipboard } from "lucide-react";

export function StaffHandoffNote({ note }: { note: string | null }) {
  if (!note) return null;

  async function copy() {
    await navigator.clipboard.writeText(note ?? "");
  }

  return (
    <section className="animate-[slideInUp_300ms_ease-out] rounded-xl border border-slate-200 bg-[#f8fafc] p-4 shadow-[0_14px_34px_rgba(15,23,42,0.07)] transition hover:border-blue-200 hover:shadow-[0_18px_42px_rgba(15,23,42,0.10)]">
      <div className="mb-3 flex items-center justify-between gap-3">
        <h2 className="text-sm font-semibold text-slate-900">Staff Prep Note</h2>
        <button className="inline-flex items-center gap-2 rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-semibold text-slate-600 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:text-blue-600 hover:shadow-md" onClick={copy} type="button">
          <Clipboard size={14} />
          Copy
        </button>
      </div>
      <p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{note}</p>
      <p className="mt-4 text-xs italic text-slate-400">Generated by ClusterCat AI</p>
    </section>
  );
}
